//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirePolicyIssuanceSystem.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalculateLcSiSoap")]
    public interface CalculateLcSiSoap {
        
        // CODEGEN: Generating message contract since element name currencyCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrency", ReplyAction="*")]
        FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse ConvertCurrency(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse> ConvertCurrencyAsync(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCurrencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertCurrency", Namespace="http://tempuri.org/", Order=0)]
        public FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequestBody Body;
        
        public ConvertCurrencyRequest() {
        }
        
        public ConvertCurrencyRequest(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertCurrencyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyType;
        
        public ConvertCurrencyRequestBody() {
        }
        
        public ConvertCurrencyRequestBody(double amount, string currencyCode, string currencyType) {
            this.amount = amount;
            this.currencyCode = currencyCode;
            this.currencyType = currencyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertCurrencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponseBody Body;
        
        public ConvertCurrencyResponse() {
        }
        
        public ConvertCurrencyResponse(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertCurrencyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConvertCurrencyResult;
        
        public ConvertCurrencyResponseBody() {
        }
        
        public ConvertCurrencyResponseBody(double ConvertCurrencyResult) {
            this.ConvertCurrencyResult = ConvertCurrencyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateLcSiSoapChannel : FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateLcSiSoapClient : System.ServiceModel.ClientBase<FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap>, FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap {
        
        public CalculateLcSiSoapClient() {
        }
        
        public CalculateLcSiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateLcSiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateLcSiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateLcSiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap.ConvertCurrency(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest request) {
            return base.Channel.ConvertCurrency(request);
        }
        
        public double ConvertCurrency(double amount, string currencyCode, string currencyType) {
            FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest inValue = new FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest();
            inValue.Body = new FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.currencyCode = currencyCode;
            inValue.Body.currencyType = currencyType;
            FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse retVal = ((FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap)(this)).ConvertCurrency(inValue);
            return retVal.Body.ConvertCurrencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse> FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap.ConvertCurrencyAsync(FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest request) {
            return base.Channel.ConvertCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyResponse> ConvertCurrencyAsync(double amount, string currencyCode, string currencyType) {
            FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest inValue = new FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequest();
            inValue.Body = new FirePolicyIssuanceSystem.ServiceReference1.ConvertCurrencyRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.currencyCode = currencyCode;
            inValue.Body.currencyType = currencyType;
            return ((FirePolicyIssuanceSystem.ServiceReference1.CalculateLcSiSoap)(this)).ConvertCurrencyAsync(inValue);
        }
    }
}
